# Generated by Django 3.2.9 on 2021-12-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('answerTo', models.CharField(max_length=100)),
                ('tage', models.CharField(max_length=50)),
            ],
        ),
    ]
